version: "3.7"

services:  
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: devoray
      MYSQL_PASSWORD: Devoray_123
    networks:
      - oraynet

  myapp:
    image: devoray/bookstore-api:latest 
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - oraynet

networks:
  enesnet:
    driver: bridge